name: issue2md

on:
    issues:
        types: [opened, edited, closed, reopened]
    issue_comment:
        types: [created, edited, deleted]
    
jobs:
    issue2md:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: sxy15/issue2md-action@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
